### ISSUE TITLE
Symptoms intialzing from general to more intricate symptoms/sicknesses

### ISSUE THREAD

**Issue by Andrew-Nguyen1** [CSAllenISD/2023-ISP-SymptomsQuiz#16]

**Comment by tejasvig12** [comment]
start off with the basics, a fever and cold

**Comment by shreyakumar66** [comment]
later we can look more closely into other symptoms since a lot of different diseases have similar symptoms

**Comment by preston-hnguyen** [comment]
I think we should compare all the symptoms of the sicknesses to see what they all have in common also.
