### ISSUE TITLE
Lets attempt to make the symptoms quiz more appealing to the eye

### ISSUE THREAD

**Issue by Andrew-Nguyen1** [CSAllenISD/2023-ISP-SymptomsQuiz#23]
I noticed in the symptoms quiz it so far is looking good but the way its laid out makes it feel too "spacious" if that makes sense due to the fact that the formatting is off. I'd like to make it to be seen more professional because it is a MEDICAL assessment.

**Comment by nxchotakuu** [comment]
I'll work on it later, any suggestions on what color schemes to add, font. layout, etc.?

**Comment by tejasvig12** [comment]
> I'll work on it later, any suggestions on what color schemes to add, font. layout, etc.?

Make the background a much lighter color, because bright blue is very unappealing. Also, create a navigation bar at the top of the screen for a home page, quiz page, and faq page. Change font to Arial or Sans-Serif, and make sure everything is completely centered.

**Comment by shreyakumar66** [comment]
> > I'll work on it later, any suggestions on what color schemes to add, font. layout, etc.?
> 
> 
> 
> Make the background a much lighter color, because bright blue is very unappealing. Also, create a navigation bar at the top of the screen for a home page, quiz page, and faq page. Change font to Arial or Sans-Serif, and make sure everything is completely centered.

i feel like it would look more professional with a white background with a few different shades of another color for accents if yk what i mean
