### ISSUE TITLE
ISP illness flowchart

### ISSUE THREAD

**Issue by nxchotakuu** [CSAllenISD/2023-ISP-SymptomsQuiz#27]
Here's the flowchart for 4 main illnesses, Shreya and I will add more illnesses later but this is our foundation. 

https://app.diagrams.net/#G1Z2eY8QAA6-4OapMCqIOjloxAAYyVi5io

**Comment by shreyakumar66** [comment]
<img width="977" alt="Screen Shot 2023-04-03 at 10 10 46 AM" src="https://user-images.githubusercontent.com/89591175/229552410-17afbf5a-8eeb-4211-81c5-f576a7b25191.png">
